name: (Release) Build Pipy, Dockerhub image and test

on:
  release:
    types: [released]

jobs:

  build-n-publish-pypi:
    name: Build and publish Python to Test PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/macapype

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  docker-build:
    name: Build Docker image and Push to Docker Hub
    needs: build-n-publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: macatools/skullTo3d

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-pretest-ants-macaque-0p5:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS macaque 0p5 CT petra)
    needs:  docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_macaque

            ls skullTo3d_CI_v2/cerimed_macaque/sub-Stevie/ses-01/anat

            echo ""

      - name: Running all test pipelines (ANTS cerimed macaque petra CT)
        run: |
            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull -data /data/cerimed_macaque -out /data/cerimed_macaque/results -soft ANTS_skullnoisypetra_robustreg_prep -species macaque_0p5 -sub Stevie -ses 01 -brain_dt T1 T2 -skull_dt ct -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque/results/derivatives/macapype_ants_skull/sub-Stevie/ses-01/anat

      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque/results


  run-pretest-ants-marmo:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS marmo CT)
    needs:  docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_marmo

            ls skullTo3d_CI_v2/cerimed_marmo/sub-Tresor/ses-01/anat

            echo ""


      - name: Running all test pipelines (ANTS cerimed marmo CT)
        run: |
            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull -data /data/cerimed_marmo -out /data/cerimed_marmo/results -soft ANTS_skull_robustreg_prep -species marmo -sub Tresor -ses 01 -brain_dt T1 T2 -skull_dt CT -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results/derivatives/macapype_ants_skull/sub-Tresor/ses-01/anat

      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results

  run-pretest-ants-marmoT2:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS marmoT2 CT)
    needs:  docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_marmo

            ls skullTo3d_CI_v2/cerimed_marmo/sub-Tresor/ses-01/anat

            echo ""


      - name: Running all test pipelines (ANTS cerimed marmoT2 CT)
        run: |
            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull -data /data/cerimed_marmo -out /data/cerimed_marmo/results -soft ANTS_skull_robustreg_prep -species marmoT2 -sub Tresor -ses 01 -brain_dt T1 T2 -skull_dt CT -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results/derivatives/macapype_ants_skull/sub-Tresor/ses-01/anat

      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo/results

