name: (Release) Build Pipy, Dockerhub image and test

on:
  release:
    types: [released]

jobs:

  build-n-publish-pypi:
    name: Build and publish Python to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  docker-build:
    name: Build Docker image and Push to Docker Hub
    needs: build-n-publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: macatools/skullTo3d

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile_nomcr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-pretest-ants-macaque-petra:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS macaque petra)
    needs:  docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_macaque_petra

            ls skullTo3d_CI_v2/cerimed_macaque_petra/sub-Gus/ses-01/anat

            echo ""

      - name: Running all test pipelines (ANTS cenir macaque petra)
        run: |
            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull -data /data/cerimed_macaque_petra -out /data/cerimed_macaque_petra/results -soft ANTS_prep_skull -species macaque -sub Gus -ses 01 -brain_dt T1 T2 -skull_dt petra -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_petra/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_petra/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_petra/results/derivatives/macapype_crop_aladin_ants_skull_petra_segbrain_t1_t2/sub-Gus/ses-01/anat

      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_petra/results/derivatives/macapype_crop_aladin_ants_skull_petra_segbrain_t1_t2

            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_petra/result/macapype_crop_aladin_ants_skull_petra_segbrain_t1_t2

  run-pretest-ants-macaque-ct:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS macaque CT)
    needs:  docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_macaque_ct

            ls skullTo3d_CI_v2/cerimed_macaque_ct/sub-Marvin/ses-01/anat

            echo ""


      - name: Running all test pipelines (ANTS cerimed macaque CT)
        run: |

            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull  -data /data/cerimed_macaque_ct -out /data/cerimed_macaque_ct/results -soft ANTS_prep_skull -species macaque -sub Marvin -ses 01 -brain_dt T1 T2 -skull_dt CT -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_ct/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_ct/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_ct/results/derivatives/macapype_crop_aladin_ants_skull_CT_segbrain_t1_t2/sub-Marvin/ses-01/anat

      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_ct/results/derivatives/macapype_crop_aladin_ants_skull_CT_segbrain_t1_t2

            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_macaque_ct/result/macapype_crop_aladin_ants_skull_CT_segbrain_t1_t2


  run-pretest-ants-marmo-petra:
    name: Running all existing pipelines in skullTo3d_CI_v2.zip (ANTS marmo petra)
    needs:  docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/skullto3d:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/7tf4ooJsyjHfSbG --output skullTo3d_CI_v2.zip
            unzip -o skullTo3d_CI_v2.zip -d skullTo3d_CI_v2

            pwd
            echo ""

            ls skullTo3d_CI_v2
            echo ""

            ls skullTo3d_CI_v2/cerimed_marmo_petra

            ls skullTo3d_CI_v2/cerimed_marmo_petra/sub-Paolina/ses-01/anat

            echo ""


      - name: Running all test pipelines (ANTS cerimed marmo petra)
        run: |
            docker run -i -v /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2:/data macatools/skullto3d:latest segment_skull -data /data/cerimed_marmo_petra -out /data/cerimed_marmo_petra/results -soft ANTS_noseg_skull -species marmo -sub Paolina -ses 01 -brain_dt T1 T2 -skull_dt T1 petra -deriv -pad -nprocs 1

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo_petra/results

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo_petra/results/derivatives

            ls /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo_petra/results/derivatives/macapype_crop_aladin_ants_skull_t1_petra_segbrain_t1_t2/sub-Paolina/ses-01/anat


      - name: Cleaning dataset
        run: |
            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo_petra/results/derivatives/macapype_crop_aladin_ants_skull_t1_petra_segbrain_t1_t2

            sudo rm -rf /home/runner/work/skullTo3d/skullTo3d/skullTo3d_CI_v2/cerimed_marmo_petra/result/macapype_crop_aladin_ants_skull_t1_petra_segbrain_t1_t2

